# Generated by Django 5.1.2 on 2024-10-28 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_agentprofile_user_alter_athleteprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='position',
            new_name='sport',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='specializations',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='sport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
