# Generated by Django 5.1.2 on 2024-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
    ]
